[pytest]
testpaths = tests
norecursedirs = tests/*
addopts = -vv --maxfail=1000 --disable-warnings --cov=simple_cloud_kit --cov-report=term-missing --cov-report=html
python_files = test_*.py
asyncio_default_fixture_loop_scope = session
env_override_existing_values = true
env_files =
    .env
